### ISSUE TITLE
[feat] create an online `nix-locate` service

### ISSUE THREAD

**Issue by loynoir** [nix-community/nix-index#234] opened 2023-09-20 15:37 UTC

**Comment by RaitoBezarius** [comment] 2023-09-20 15:46
search.nixos.org ?

**Comment by loynoir** [comment] 2023-09-20 15:57
@RaitoBezarius 

- `search.nixos.org` seems not support search package using file.

- https://pkgs.alpinelinux.org/contents

**Comment by RaitoBezarius** [comment] 2023-09-20 16:23
Then, shouldn't this be a feature request with search.nixos.org to add a /contents URL and use the locate database inside the browser?

**Comment by SuperSandro2000** [comment] 2023-09-29 11:33
dupe of #194

**Closed** 2023-09-30 23:03 UTC
